### ISSUE TITLE
Note to reviewer

### ISSUE THREAD

**Issue by 0sugo** [0sugo/appointment_booker_backend#23]
Hello reviewer:
This project has onboard 3 people:
@oguntayomicheal , @0sugo , @UbdaNam 

[Here is the link to the kanban board](https://github.com/0sugo/Final_Capstone/projects/1).Where we are going to build an app that allows users to book appointments with specific doctors on the site.

Here is a screenshot of the kanban board
![kanban board](https://github.com/0sugo/appointment_booker_backend/assets/113665157/e963eda6-8a82-438f-bb38-5f4d3938bdc6)

**Comment by Meltrust** [comment]
Hi @0sugo,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



### To highlight:

- All cards have been assigned✔️ 

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

## Required Changes ♻️

- [ ] Kindly, add some points to this card:

![image](https://github.com/0sugo/appointment_booker_backend/assets/57421823/be9f22b9-53cd-47ce-8389-dc936d1ad7ed)

![image](https://github.com/0sugo/appointment_booker_backend/assets/57421823/1bfca48d-e523-42aa-8db2-81ea27546e27)

That way, we will meet this particular [requirement](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/setup_kanban_board.md). 👍 

_note:  When adding points to the card, kindly remember to preserve the limit of no more than 5 total points of difference among any member of the team._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
